version: '3.8'

services:
  langgraph-server:
    build:
      context: .
      dockerfile: Dockerfile.langgraph
    container_name: langgraph-chatbot
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PORT=8000
    volumes:
      # Mount data directory for persistent storage
      - ./data:/app/data
      # Mount JSON file for Q&A data
      - ./browser_agent_test_output.json:/app/browser_agent_test_output.json
      # Mount SQLite checkpoint database
      - ./langgraph_checkpoints.db:/app/langgraph_checkpoints.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
    driver: local
